language: java
jdk:
  - oraclejdk8
sudo: required
services:
  - redis
  - docker
after_success:
  - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
  - docker-compose build
  - docker-compose push