language: java
jdk:
  - oraclejdk8
notifications:
  email: false
  irc:
    channels:
      - "irc.esper.net#year4000"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Build details : %{build_url}"
    use_notice: true
    skip_join: true
services: redis
