---
# CircleCI Config to build Utilities and Deploy Docker Images
version: 2

jobs:
    build:
        docker:
            - image: sgrio/java-oracle:latest
        steps:
            - checkout
            - run: ./gradlew clean build test

    # Deploy the Docker image
    deploy:
        machine:
            enabled: true
        steps:
            - run: docker login -e ${DOCKER_EMAIL} -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
            - run: docker-compose build
            - run: docker-compose push


workflows:
    version: 2
    build-deploy:
        jobs:
            - build
            - deploy:
                  requires:
                      - build
                  filters:
                      branches:
                          only: master
