---
# CircleCI Config to build Utilities and Deploy Docker Images
version: 2

jobs:
    build:
        docker:
            - image: isuper/java-oracle:latest
        steps:
            - checkout
            - run: ./gradlew clean build test
            - store_artifacts:
                  - path: core/build/libs/
            - store_artifacts:
                  - path: core-ducktape/build/libs/
            - store_artifacts:
                  - path: core-locale/build/libs/
            - store_artifacts:
                  - path: core-minecraft/build/libs/
            - store_artifacts:
                  - path: core-redis/build/libs/
            - store_artifacts:
                  - path: core-scheduler/build/libs/
            - store_artifacts:
                  - path: core-sdk/build/libs/
            - store_artifacts:
                  - path: gradle/build/libs/gradle-sources.jar
            - store_artifacts:
                  - path: sponge/build/libs/

    # Deploy the Docker image
    deploy:
        machine:
            enabled: true
        steps:
            - run: docker login -e ${DOCKER_EMAIL} -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
            - run: docker-compose build
            - run: docker-compose push


workflows:
    version: 2
    build-deploy:
        jobs:
            - build
            - deploy:
                  requires:
                      - build
                  filters:
                      branches:
                          only: master
