/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_year4000_utilities_ducktape_loaders_v8_V8 */

#ifndef _Included_net_year4000_utilities_ducktape_loaders_v8_V8
#define _Included_net_year4000_utilities_ducktape_loaders_v8_V8
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_year4000_utilities_ducktape_loaders_v8_V8
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_year4000_utilities_ducktape_loaders_v8_V8_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
